export const SET_SOURCE_CURRENCY = 'SET_SOURCE_CURRENCY';
export const SET_DESTINATION_CURRENCY = 'SET_DESTINATION_CURRENCY';
export const SWAP_CURRENCIES = 'SWAP_CURRENCIES';
export const SET_SOURCE_AMOUNT = 'SET_SOURCE_AMOUNT';
export const SET_DESTINATION_AMOUNT = 'SET_DESTINATION_AMOUNT';
export const SET_RATE = 'SET_RATE';
